Ubuntu ethos 하위 문서 번역 및 업데이트
ubuntu-kr/disclosures.ubuntu-kr.org pull request #6
Opened 2024-04-30 15:01 UTC by NayeonKeum

작업 진행 중 입니다.

2024-05-11 13:03 UTC, sukso96100 requested changes
전반적으로 번역 개선 잘 해 주셨습니다 :) 몇가지 체크해서 더 개선할 부분이 있는데

- `mission.md`에서 언급되는 `Free`, `Free Software` 등은 돈 안주고 다운받아서 쓰는 `무료`의 맥락이 아니라 소스코드에 제한 없이 누구나 **자유**롭게 접근과 수정 및 실행이 가능한 `자유` 맥락입니다. 참고해서 수정 해 주세요.
- 행동강령에서 커뮤니티 기구에 대한 부분이 나오는데 (Community Council, SABDFL, 하위 Council 이나 Committee 등) 이전에 언급 한 것 처럼 Council 이나 Committee 에 대한 용어가 통일되면 좋을 듯 합니다. 거버넌스 관련 문서를 보시면 적절한 용어 하나 골라서 통일하는데 도움이 될듯 합니다 https://ubuntu.com/community/governance

2024-05-11 13:03 UTC, sukso96100 commented on docs/legal/ethos/mission.md
> +### 무료 소프트웨어
여기에서의 Free 는 "무로" 가 아닌 "자유" 를 의미합니다.
Free Software, Free Software Foundation 이 무료 소프트웨어, 무료 소프트웨어 재단이 아닌 자유 소프트웨어와, 자유 소프트웨어 재단으로 번역되는 것을 생각 하시면 됩니다. 참고해서 다른 부분에 잘못 번역된 부분 있다면 수정 해 주세요

2024-05-11 13:03 UTC, sukso96100 commented on docs/legal/ethos/mission.md
> +* 프로그램을 개선하고 개선 사항을 대중에게 공개하여 모든 사람이 이익을 얻을 수 있는 자유
```suggestion
* 모든 사람이 혜택을 받을 수 있도록, 프로그램을 개선하고 개선 사항을 대중에게 공개할 자유
```

2024-05-11 13:03 UTC, sukso96100 commented on docs/legal/ethos/mission.md
> +오픈 소스라는 용어는 1998년 '무료(free)'라는 단어의 모호함을 제거하기 위해 만들어졌고, 이후에도 점점 더 성공적으로 널리 인정받고 있습니다. 비록 어떤 사람들은 '무료'와 '오픈 소스'를 서로 다른 목적을 가진 경쟁 운동으로 간주하지만, 우리는 그렇게 생각하지 않습니다. 우분투에는 자랑스럽게도 둘 다 공감하는 회원들이 포함되어 있습니다.
무료(free) 는 무료와 자유의 의미 둘다 가지기 때문에 혼동할 수 있음을 알 수 있게 번역하면 좋을 듯 합니다. "무료(혹은 자유 - free)" 로 하는 방법도 있을 듯 하구요.

자유 소프트웨어 운동과 오픈소스 소프트웨어 운동 맥락이여서 `'무료'와 '오픈 소스'를` -> `'자유'와 '오픈 소스'를`로 바꾸는 것이 좋겠습니다.

2024-05-11 13:03 UTC, sukso96100 commented on docs/legal/ethos/mission.md
> +1998년에 만들어진 오픈 소스라는 용어는 1950년대 컴퓨팅의 여명기 이후 강력해진 협력 세력인 무료 소프트웨어 운동에서 비롯되었습니다. 이 초기 커뮤니티는 최초의 운영 체제, 소프트웨어 및 1969년에 인터넷 자체의 많은 개발을 담당했습니다.
```suggestion
1998년에 만들어진 오픈 소스라는 용어는 1950년대 컴퓨팅의 여명기 이후 강력해진 협력 세력인 자유 소프트웨어 운동에서 비롯되었습니다. 이 초기 커뮤니티는 최초의 운영 체제, 소프트웨어 및 1969년에 인터넷 자체의 많은 개발을 담당했습니다.
```
마찬가지로 소프트웨어를 공짜로 풀자는 "무료"의 의미가 아니라, 소스코드에 제안없이 자유롭게 접근할 수 있게 하자는 의미의 "자유"의 맥락 입니다.

2024-05-11 13:03 UTC, sukso96100 commented on docs/legal/ethos/code-of-conduct.md
> +### 갈등을 커뮤니티 평의회로 보고하기
커뮤니티 평의회 는 원문이 Community Council 인가요?

2024-05-11 13:34 UTC, NayeonKeum commented on docs/legal/ethos/mission.md
> +### 무료 소프트웨어
확인했습니다!

2024-05-11 13:34 UTC, NayeonKeum commented on docs/legal/ethos/mission.md
> +* 프로그램을 개선하고 개선 사항을 대중에게 공개하여 모든 사람이 이익을 얻을 수 있는 자유
확인했습니다!

2024-05-11 13:34 UTC, NayeonKeum commented on docs/legal/ethos/mission.md
> +오픈 소스라는 용어는 1998년 '무료(free)'라는 단어의 모호함을 제거하기 위해 만들어졌고, 이후에도 점점 더 성공적으로 널리 인정받고 있습니다. 비록 어떤 사람들은 '무료'와 '오픈 소스'를 서로 다른 목적을 가진 경쟁 운동으로 간주하지만, 우리는 그렇게 생각하지 않습니다. 우분투에는 자랑스럽게도 둘 다 공감하는 회원들이 포함되어 있습니다.
확인했습니다!

2024-05-11 13:35 UTC, NayeonKeum commented on docs/legal/ethos/mission.md
> +1998년에 만들어진 오픈 소스라는 용어는 1950년대 컴퓨팅의 여명기 이후 강력해진 협력 세력인 무료 소프트웨어 운동에서 비롯되었습니다. 이 초기 커뮤니티는 최초의 운영 체제, 소프트웨어 및 1969년에 인터넷 자체의 많은 개발을 담당했습니다.
확인했습니다!

2024-05-11 13:35 UTC, NayeonKeum commented on docs/legal/ethos/code-of-conduct.md
> +### 갈등을 커뮤니티 평의회로 보고하기
넵 용어 통일이 필요할듯 합니다

2024-05-12 07:45 UTC, sukso96100 commented on docs/legal/ethos/code-of-conduct.md
> +### 갈등을 커뮤니티 평의회로 보고하기
그러면 용어 관련해서는 논의가 시간이 좀 걸릴 듯 하니, #8 에서 논의 어느정도 되면 그때 별도 PR로 다루는 것으로 하시죠 :)

2024-05-12 07:46 UTC, sukso96100 approved these changes

2024-05-12 07:46 UTC, merged